// Generated from textures-codex/library/manifest.json — do not hand-edit.
// Regenerate with the same source manifest if textures are added or changed.

export interface TextureManifestEntryV2 {
  id: string;
  /**
   * File name inside the texture library. Resolve it with `textureUrl(file)`
   * from ./asset-urls — the library is served from Supabase Storage, not from
   * frontend/public.
   */
  file: string;
  kind: string;
  tileable: boolean;
  tags: string[];
  suggestedUse?: string;
  license: string;
}

export const TEXTURE_MANIFEST_V2: readonly TextureManifestEntryV2[] = [
  {
    id: "debris-01",
    file: "debris-01.png",
    kind: "decal",
    tileable: false,
    tags: [
      "debris",
      "ground",
      "rubble",
      "impact",
    ],
    suggestedUse: "ground debris scatter; alpha blend; scale/rotate randomly per instance",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "droplet-01",
    file: "droplet-01.png",
    kind: "decal",
    tileable: false,
    tags: [
      "water",
      "droplet",
      "liquid",
      "splash",
    ],
    suggestedUse: "water droplet decal; alpha blend; scatter on impact or rain splash",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "ember-01",
    file: "ember-01.png",
    kind: "glow",
    tileable: false,
    tags: [
      "fire",
      "ember",
      "glow",
      "particle",
    ],
    suggestedUse: "floating ember particle; additive blend; drift upward with fade",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flame-lick-cluster-01",
    file: "flame-lick-cluster-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "fire",
      "flame",
      "cluster",
      "glow",
    ],
    suggestedUse: "flame cluster body; additive blend; animate with scroll/noise distortion",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flame-tongue-01",
    file: "flame-tongue-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "fire",
      "flame",
      "tongue",
      "glow",
    ],
    suggestedUse: "single flame tongue; additive blend; vertical stretch and flicker",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flame-tongue-02",
    file: "flame-tongue-02.png",
    kind: "mask",
    tileable: false,
    tags: [
      "fire",
      "flame",
      "tongue",
      "glow",
    ],
    suggestedUse: "single flame tongue variant; additive blend; vertical stretch and flicker",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flipbook-burst-6x6",
    file: "flipbook-burst-6x6.png",
    kind: "flipbook",
    tileable: false,
    tags: [
      "burst",
      "explosion",
      "impact",
      "animation",
    ],
    suggestedUse: "6x6 burst flipbook; play once on impact; additive blend",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flipbook-fire-8x8",
    file: "flipbook-fire-8x8.png",
    kind: "flipbook",
    tileable: false,
    tags: [
      "fire",
      "flame",
      "loop",
      "animation",
    ],
    suggestedUse: "8x8 fire flipbook; loop; additive blend for flame body",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "flipbook-smoke-8x8",
    file: "flipbook-smoke-8x8.png",
    kind: "flipbook",
    tileable: false,
    tags: [
      "smoke",
      "loop",
      "animation",
    ],
    suggestedUse: "8x8 smoke flipbook; loop; alpha blend, tint dark-to-light",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "frost-01",
    file: "frost-01.png",
    kind: "decal",
    tileable: false,
    tags: [
      "ice",
      "frost",
      "overlay",
      "cold",
    ],
    suggestedUse: "frost/ice overlay decal; alpha blend on surfaces; static or slow fade-in",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "glitter-01",
    file: "glitter-01.png",
    kind: "glow",
    tileable: false,
    tags: [
      "sparkle",
      "glitter",
      "particle",
      "magic",
    ],
    suggestedUse: "glitter/sparkle overlay; additive blend; animate with scroll for twinkle",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "ground-glow-01",
    file: "ground-glow-01.png",
    kind: "glow",
    tileable: false,
    tags: [
      "ground",
      "glow",
      "aoe",
      "magic",
    ],
    suggestedUse: "ground AoE glow decal; additive blend; scale for radius, pulse opacity",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "ice-shard-01",
    file: "ice-shard-01.png",
    kind: "shape",
    tileable: false,
    tags: [
      "ice",
      "shard",
      "crystal",
      "weapon",
    ],
    suggestedUse: "ice shard shape; alpha blend; scatter or use as projectile sprite",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "magic-sigil-01",
    file: "magic-sigil-01.png",
    kind: "sigil",
    tileable: false,
    tags: [
      "magic",
      "sigil",
      "rune",
      "cast",
    ],
    suggestedUse: "magic cast sigil; additive blend; rotate slowly, scale in on cast",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "mask-glow-cross-01",
    file: "mask-glow-cross-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "glow",
      "cross",
      "beam",
      "utility",
    ],
    suggestedUse: "cross-shaped glow mask; additive blend; use as lens flare or beam core",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "mask-soft-01",
    file: "mask-soft-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "soft",
      "gradient",
      "utility",
      "glow",
    ],
    suggestedUse: "soft radial falloff mask; alpha blend; multiply into custom-colored glows",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "mask-soft-02",
    file: "mask-soft-02.png",
    kind: "mask",
    tileable: false,
    tags: [
      "soft",
      "gradient",
      "utility",
      "glow",
    ],
    suggestedUse: "soft radial falloff mask variant; alpha blend; multiply into custom glows",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "mask-soft-03",
    file: "mask-soft-03.png",
    kind: "mask",
    tileable: false,
    tags: [
      "soft",
      "gradient",
      "utility",
      "glow",
    ],
    suggestedUse: "soft radial falloff mask variant; alpha blend; multiply into custom glows",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "noise-cloud-tile-01",
    file: "noise-cloud-tile-01.png",
    kind: "noise",
    tileable: true,
    tags: [
      "noise",
      "cloud",
      "tileable",
      "erosion",
    ],
    suggestedUse: "tileable cloud noise; use as erosion/dissolve mask or smoke detail texture",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "noise-cloud-tile-02",
    file: "noise-cloud-tile-02.png",
    kind: "noise",
    tileable: true,
    tags: [
      "noise",
      "cloud",
      "tileable",
      "erosion",
    ],
    suggestedUse: "tileable cloud noise variant; use as erosion/dissolve mask or smoke detail",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "noise-streak-tile-01",
    file: "noise-streak-tile-01.png",
    kind: "noise",
    tileable: true,
    tags: [
      "noise",
      "streak",
      "tileable",
      "motion",
    ],
    suggestedUse: "tileable streak noise; use for motion trails or directional erosion",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "ring-gradient-01",
    file: "ring-gradient-01.png",
    kind: "ring",
    tileable: false,
    tags: [
      "ring",
      "gradient",
      "shockwave",
      "aoe",
    ],
    suggestedUse: "gradient ring shockwave; additive blend; scale outward and fade for AoE pulse",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "ring-soft-01",
    file: "ring-soft-01.png",
    kind: "ring",
    tileable: false,
    tags: [
      "ring",
      "soft",
      "aoe",
      "indicator",
    ],
    suggestedUse: "soft ring indicator; alpha blend; use for AoE range indicator or target marker",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "scorch-01",
    file: "scorch-01.png",
    kind: "decal",
    tileable: false,
    tags: [
      "scorch",
      "burn",
      "ground",
      "decal",
    ],
    suggestedUse: "scorch mark ground decal; alpha blend; static, place after fire impact",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "smoke-puff-01",
    file: "smoke-puff-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "smoke",
      "puff",
      "cloud",
      "particle",
    ],
    suggestedUse: "smoke puff particle; alpha blend; expand and fade upward",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "smoke-puff-02",
    file: "smoke-puff-02.png",
    kind: "mask",
    tileable: false,
    tags: [
      "smoke",
      "puff",
      "cloud",
      "particle",
    ],
    suggestedUse: "smoke puff particle variant; alpha blend; expand and fade upward",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "smoke-puff-03",
    file: "smoke-puff-03.png",
    kind: "mask",
    tileable: false,
    tags: [
      "smoke",
      "puff",
      "cloud",
      "particle",
    ],
    suggestedUse: "smoke puff particle variant; alpha blend; expand and fade upward",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "smoke-wisp-01",
    file: "smoke-wisp-01.png",
    kind: "mask",
    tileable: false,
    tags: [
      "smoke",
      "wisp",
      "trail",
      "particle",
    ],
    suggestedUse: "thin smoke wisp/trail; alpha blend; drift and stretch along path",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "smoke-wisp-02",
    file: "smoke-wisp-02.png",
    kind: "mask",
    tileable: false,
    tags: [
      "smoke",
      "wisp",
      "trail",
      "particle",
    ],
    suggestedUse: "thin smoke wisp/trail variant; alpha blend; drift and stretch along path",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "spark-dot-01",
    file: "spark-dot-01.png",
    kind: "glow",
    tileable: false,
    tags: [
      "spark",
      "dot",
      "particle",
      "glint",
    ],
    suggestedUse: "small spark/glint dot; additive blend; random scatter with fast fade",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "spark-streak-01",
    file: "spark-streak-01.png",
    kind: "streak",
    tileable: false,
    tags: [
      "spark",
      "streak",
      "trail",
      "motion",
    ],
    suggestedUse: "spark streak trail; additive blend; align to velocity vector",
    license: "generated in-house (Images API), MIT",
  },
  {
    id: "spark-streak-02",
    file: "spark-streak-02.png",
    kind: "streak",
    tileable: false,
    tags: [
      "spark",
      "streak",
      "trail",
      "motion",
    ],
    suggestedUse: "spark streak trail variant; additive blend; align to velocity vector",
    license: "generated in-house (Images API), MIT",
  },
] as const;
