import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".eve/**",
    ".output/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "public/vfx-runtime.js",
    "public/vfx-runtime-v2.js",
    "src/lib/vfx-lab/shaders-v2-nodes.js", // Generated by scripts/webgpu/port-shaders.mts.
    "public/trial-presets/**", // Generated output; lint the scripts/shared-trials source instead.
    ".autov-local/**",
    "test-results/**",
    "playwright-report/**",
  ]),
]);

export default eslintConfig;
