/** One-time, reproducible migration of the authored V2 shader math to TSL.
 * Runs offline; the browser imports static node factories, never a GLSL parser.
 */
import {
  braceBodies,
  copyMutatedParameters,
  lowerEarlyReturns,
} from "./lower-returns.mjs";
import { mkdir, writeFile } from "node:fs/promises";
import GLSLDecoder from "three/addons/transpiler/GLSLDecoder.js";
import TSLEncoder from "three/addons/transpiler/TSLEncoder.js";
import Transpiler from "three/addons/transpiler/Transpiler.js";
import {
  particleVertexSource,
  trailVertexSource,
  stripVertexSource,
  sliverVertexSource,
  particleFragmentV2,
  trailFragmentV2,
  stripFragmentV2,
  sliverFragmentV2,
  surfaceVertexV2,
  surfaceFragmentV2,
  blobVertexV2,
  blobFragmentV2,
  crystalVertexV2,
  crystalFragmentV2,
  splashVertexV2,
  splashFragmentV2,
  ribbonVertexV2,
  ribbonFragmentV2,
  wireBurstVertexV2,
  wireBurstFragmentV2,
  arcVertexV2,
  arcFragmentV2,
  streakVertexV2,
  streakFragmentV2,
  sheetVertexV2,
  sheetFragmentV2,
  crescentVertexV2,
  crescentFragmentV2,
  lickVertexV2,
  lickFragmentV2,
} from "../../src/lib/vfx-lab/shaders-v2";

// The optional instance attributes (borrowed spawn sites, resolved path events)
// are always declared: the branches that read them are already gated on
// uniforms, and the runtime always supplies the buffers, so one program covers
// every emitter instead of a variant per attribute set.
const sources: Record<string, string> = {
  particleVertex: particleVertexSource(false, true, true),
  subParticleVertex: particleVertexSource(true, true, true),
  trailVertex: trailVertexSource(false, true, true),
  subTrailVertex: trailVertexSource(true, true, true),
  stripVertex: stripVertexSource(true, true),
  sliverVertex: sliverVertexSource(true, true),
  particleFragment: particleFragmentV2,
  trailFragment: trailFragmentV2,
  stripFragment: stripFragmentV2,
  sliverFragment: sliverFragmentV2,
  surfaceVertex: surfaceVertexV2,
  surfaceFragment: surfaceFragmentV2,
  blobVertex: blobVertexV2,
  blobFragment: blobFragmentV2,
  crystalVertex: crystalVertexV2,
  crystalFragment: crystalFragmentV2,
  splashVertex: splashVertexV2,
  splashFragment: splashFragmentV2,
  ribbonVertex: ribbonVertexV2,
  ribbonFragment: ribbonFragmentV2,
  wireBurstVertex: wireBurstVertexV2,
  wireBurstFragment: wireBurstFragmentV2,
  arcVertex: arcVertexV2,
  arcFragment: arcFragmentV2,
  streakVertex: streakVertexV2,
  streakFragment: streakFragmentV2,
  sheetVertex: sheetVertexV2,
  sheetFragment: sheetFragmentV2,
  crescentVertex: crescentVertexV2,
  crescentFragment: crescentFragmentV2,
  lickVertex: lickVertexV2,
  lickFragment: lickFragmentV2,
};

const TYPES =
  "void|bool|int|float|vec2|vec3|vec4|ivec2|ivec3|ivec4|mat2|mat3|mat4";

/** Helpers that become real WGSL functions instead of being inlined at every
 * call site: those touching no binding at all, taking no `out` parameter, and
 * calling only other such helpers.
 *
 * A uniform read inside a generated WGSL function is only recorded in the
 * shader's uniform struct on the build that first sees it; a later rebuild (a
 * diagnostic or post-free pass) emits a function referring to a struct member
 * that is no longer declared. Uniform-dependent helpers therefore stay inline,
 * and the single-exit lowering keeps their guard chains flat so that inlining
 * stays cheap. */
function pureHelpers(source: string, bindings: Map<string, string>) {
  const header = new RegExp(`\\b(${TYPES})\\s+(\\w+)\\s*\\(([^)]*)\\)\\s*\\{`, "g");
  const functions: { name: string; params: string; body: string }[] = [];
  for (let match; (match = header.exec(source)); ) {
    let depth = 1;
    let i = header.lastIndex;
    for (; i < source.length && depth; i++) {
      if (source[i] === "{") depth++;
      else if (source[i] === "}") depth--;
    }
    functions.push({
      name: match[2],
      params: match[3],
      body: source.slice(header.lastIndex, i - 1),
    });
    header.lastIndex = i;
  }
  const names = new Set(functions.map((fn) => fn.name));
  const words = (text: string) => text.match(/[A-Za-z_]\w*/g) ?? [];
  const pure = new Set<string>();
  for (let changed = true; changed; ) {
    changed = false;
    for (const fn of functions) {
      if (pure.has(fn.name) || fn.name === "main") continue;
      if (/\bout\s+\w/.test(fn.params)) continue;
      const used = words(fn.body);
      if (used.some((word) => bindings.has(word))) continue;
      if (/\b(discard|texture2D|texture|dFdx|dFdy|fwidth|gl_\w+)\b/.test(fn.body))
        continue;
      if (used.some((word) => names.has(word) && word !== fn.name && !pure.has(word)))
        continue;
      pure.add(fn.name);
      changed = true;
    }
  }
  return pure;
}

let output =
  '// Generated by scripts/webgpu/port-shaders.mts. Static TSL; no runtime GLSL or eval.\nimport * as TSL from "three/tsl";\n';
for (const [name, original] of Object.entries(sources)) {
  const bindings: Record<
    string,
    { type: string; size?: number; kind: string }
  > = {};
  const vertex = name.endsWith("Vertex");
  // The interpolated clip position stands in for gl_FragCoord, which WebGPU
  // reports in the same top-left origin the depth texture uses.
  const declared = copyMutatedParameters(
    original.includes("gl_FragCoord") || vertex
      ? "varying vec4 vClipPosition;\n" + original
      : original,
  );
  // Declarations are read before lowering so the purity analysis — and so the
  // decision of which helpers keep a WGSL function — runs on the original.
  // Comments are blanked first: the authored prose mentions these keywords.
  const scanned = declared.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, (text: string) =>
    text.replace(/[^\n]/g, " "),
  );
  let stripped = "";
  let cursor = 0;
  for (const match of scanned.matchAll(
    /\b(uniform|attribute|varying)\s+(\w+)\s+([^;]+);/g,
  )) {
    for (const variable of match[3].split(",")) {
      const parsed = variable.trim().match(/^(\w+)(?:\[(\d+)\])?$/);
      if (!parsed)
        throw new Error(
          `${name}: cannot parse declaration ${JSON.stringify(match[0])}`,
        );
      bindings[parsed[1]] = {
        type: match[2],
        size: parsed[2] ? Number(parsed[2]) : undefined,
        kind: match[1],
      };
    }
    stripped += declared.slice(cursor, match.index);
    cursor = match.index + match[0].length;
  }
  stripped += declared.slice(cursor);
  const pure = pureHelpers(
    stripped,
    new Map(
      Object.entries(bindings).map(([key, binding]) => [
        key,
        binding.type === "sampler2D" ? "sampler2D" : binding.kind,
      ]),
    ),
  );
  let lowered: string;
  try {
    lowered = lowerEarlyReturns(braceBodies(stripped), pure);
  } catch (error) {
    throw new Error(`${name}: ${(error as Error).message}`);
  }
  let source = lowered.replace(/precision\s+\w+\s+\w+;/g, "");
  // Custom vertexNode returns clip space; cameraProjectionMatrix already uses WebGPU depth.
  const result = vertex ? "gl_Position" : "gl_FragColor";
  source = source.replace(/void main\(\)/, `vec4 main()`);
  // The kill helper writes the same output variable as main.
  source = `vec4 ${result};\n${source}`;
  const end = source.lastIndexOf("}");
  source = source.slice(0, end) + `return ${result};\n` + source.slice(end);
  // WebGPU fragment and depth texture coordinates both have a top-left origin.
  source = source.replace(
    /gl_Position=([^;]+);/g,
    "gl_Position=$1; vClipPosition=gl_Position;",
  );
  source = source
    .replace(/gl_FragCoord.z/g, "(vClipPosition.z/vClipPosition.w)")
    .replace(/gl_FragCoord/g, "screenCoordinate");
  const outParams = new Set(
    [...source.matchAll(/\bout\s+\w+\s+(\w+)/g)].map((match) => match[1]),
  );
  class PortEncoder extends TSLEncoder {
    emitFunction(node: Parameters<TSLEncoder["emitFunction"]>[0]) {
      (node as typeof node & { layout: boolean }).layout = pure.has(node.name);
      const code = super.emitFunction(node);
      // Inline void functions must be added to the TSL statement stack. Without
      // an explicit void type, calls whose result is unused are never executed
      // (particle trajectories and inactive-particle clipping included).
      return node.type === "void"
        ? code.replace(/\} \);\n$/, "}, 'void' );\n")
        : code;
    }
    emitVariables(
      node: Parameters<TSLEncoder["emitVariables"]>[0],
      root = true,
    ) {
      const next = node.next;
      node.next = null;
      (node as typeof node & { needsToVar: boolean }).needsToVar = Boolean(
        node.value,
      );
      let result = super.emitVariables(node, root);
      node.next = next;
      if (next) result += ", " + this.emitVariables(next, false);
      return result;
    }
  }
  // AUTOV_DUMP writes what the transpiler is actually handed. A shader problem
  // is usually a lowering problem, and the lowered GLSL is what shows it.
  if (process.env.AUTOV_DUMP) {
    await mkdir(process.env.AUTOV_DUMP, { recursive: true });
    await writeFile(`${process.env.AUTOV_DUMP}/${name}.glsl`, source);
  }
  const encoder = new PortEncoder();
  encoder.iife = true;
  const decoder = new GLSLDecoder();
  let code = new Transpiler(decoder, encoder).parse(source);
  // The decoder stops quietly when it loses the source; a program missing its
  // entry point would otherwise only surface as a runtime ReferenceError.
  if (!code.includes("const main = "))
    throw new Error(`${name}: the transpiler dropped main()`);
  code = code
    .replace(
      "( function ( TSL, uniforms ) {",
      `export function ${name}( bindings ) {`,
    )
    .replace(/\n\} \);\s*$/, "\n}")
    .replace(/return \{[^\n]+\};\n(?=\n\})/, "return main();\n");
  code = code.replace(/(\w+)\[\s*(\d+)\s*\]/g, "$1.element($2)");
  code = code.replace(/\b(false|true)\.toVar\(\)/g, "TSL.bool($1).toVar()");
  // A negated float literal at the head of an expression (GLSL `-.5*a`) comes
  // back as `- .5.mul( a )`, which is not valid JavaScript.
  code = code.replace(
    /([(,]\s*)- (\.?\d[\d.]*)\.(?=[a-zA-Z_])/g,
    "$1TSL.float(-$2).",
  );
  const literalCall = /(?<![\w.])\d*\.\d*\.[a-zA-Z_]/.exec(code);
  if (literalCall)
    throw new Error(
      `${name}: a number literal is used as a node (${literalCall[0]})`,
    );
  // out parameters must retain the caller's variable, rather than copying it.
  for (const parameter of outParams) {
    code = code
      .replace(
        new RegExp(`const ${parameter} = ${parameter}_immutable\\.toVar\\(\\);`, "g"),
        "",
      )
      .replace(new RegExp(`\\b${parameter}_immutable\\b`, "g"), parameter);
  }
  code = code.replace(
    /const \{ ([^}]+) \} = TSL;/,
    (_, names) =>
      "const { " +
      names
        .split(", ")
        .filter(
          (n: string) =>
            !["uv", "modelViewMatrix", "screenCoordinate", "frontFacing"].includes(
              n,
            ),
        )
        .join(", ") +
      " } = TSL;",
  );
  const preamble = Object.keys(bindings)
    .map((key) => `const ${key} = bindings.${key};`)
    .join("\n");
  const builtin = `const { cameraProjectionMatrix: projectionMatrix, modelViewMatrix, modelWorldMatrix: modelMatrix, cameraViewMatrix: viewMatrix, normalLocal: normal, positionLocal: position, screenCoordinate, frontFacing: gl_FrontFacing } = TSL;\nconst uv = TSL.uv();\n`;
  code = code.replace(
    /(export function [^{]+\{)/,
    `$1\n${preamble}\n${builtin}`,
  );
  output += "\n" + code + "\n";
  output += `export const ${name}Bindings = ${JSON.stringify(bindings)};\n`;
}
await writeFile("src/lib/vfx-lab/shaders-v2-nodes.js", output);
