/** One-time, reproducible migration of the authored V2 shader math to TSL.
 * Runs offline; the browser imports static node factories, never a GLSL parser.
 */
import { lowerReturns } from "./lower-returns.mjs";
import { writeFile } from "node:fs/promises";
import GLSLDecoder from "three/addons/transpiler/GLSLDecoder.js";
import TSLEncoder from "three/addons/transpiler/TSLEncoder.js";
import Transpiler from "three/addons/transpiler/Transpiler.js";
import {
  particleVertexSource,
  trailVertexSource,
  particleFragmentV2,
  trailFragmentV2,
  surfaceVertexV2,
  surfaceFragmentV2,
} from "../../src/lib/vfx-lab/shaders-v2";
const sources = {
  particleVertex: particleVertexSource(false),
  subParticleVertex: particleVertexSource(true),
  trailVertex: trailVertexSource(false),
  subTrailVertex: trailVertexSource(true),
  particleFragment: particleFragmentV2,
  trailFragment: trailFragmentV2,
  surfaceVertex: surfaceVertexV2,
  surfaceFragment: surfaceFragmentV2,
};
let output =
  '// Generated by scripts/webgpu/port-shaders.mts. Static TSL; no runtime GLSL or eval.\nimport * as TSL from "three/tsl";\n';
for (const [name, original] of Object.entries(sources)) {
  const bindings: Record<
    string,
    { type: string; size?: number; kind: string }
  > = {};
  const lowered: string = lowerReturns(original);
  let source = (
    original.includes("gl_FragCoord") || name.endsWith("Vertex")
      ? "varying vec4 vClipPosition;\n" + lowered
      : lowered
  )
    .replace(/precision\s+\w+\s+\w+;/g, "")
    .replace(
      /\b(uniform|attribute|varying)\s+(\w+)\s+([^;]+);/g,
      (_, kind, type, vars) => {
        for (const variable of vars.split(",")) {
          const match = variable.trim().match(/^(\w+)(?:\[(\d+)\])?$/)!;
          bindings[match[1]] = {
            type,
            size: match[2] ? Number(match[2]) : undefined,
            kind,
          };
        }
        return "";
      },
    );
  const vertex = name.endsWith("Vertex");
  // Custom vertexNode returns clip space; cameraProjectionMatrix already uses WebGPU depth.
  const result = vertex ? "gl_Position" : "gl_FragColor";
  source = source.replace(/void main\(\)/, `vec4 main()`);
  source = source.replace(
    /if\(dead\)\{ kill\(\); return; \}/,
    "if(dead){ kill(); } else {",
  );
  if (original.includes("if(dead){ kill(); return; }")) {
    const last = source.lastIndexOf("}");
    source = source.slice(0, last) + "}\n" + source.slice(last);
  }
  // The kill helper writes the same output variable as main.
  source = `vec4 ${result};\n${source}`;
  source = source.replace(/return\s*;/g, `return ${result};`);
  const end = source.lastIndexOf("}");
  source = source.slice(0, end) + `return ${result};\n` + source.slice(end);
  // WebGPU fragment and depth texture coordinates both have a top-left origin.
  source = source.replace(
    /gl_Position=([^;]+);/g,
    "gl_Position=$1; vClipPosition=gl_Position;",
  );
  source = source
    .replace(/gl_FragCoord.z/g, "(vClipPosition.z/vClipPosition.w)")
    .replace(/gl_FragCoord/g, "screenCoordinate");
  class PortEncoder extends TSLEncoder {
    emitFunction(node: Parameters<TSLEncoder["emitFunction"]>[0]) {
      (node as typeof node & { layout: boolean }).layout = [
        "mod289v3",
        "mod289v4",
        "permute289",
        "taylorInvSqrtV",
        "snoise",
        "fbm3",
        "curl3",
        "safeDir",
        "safePow",
        "pointedShape",
        "hexCells",
        "proceduralShape",
      ].includes(node.name);
      const code = super.emitFunction(node);
      // Inline void functions must be added to the TSL statement stack. Without
      // an explicit void type, calls whose result is unused are never executed
      // (particle trajectories and inactive-particle clipping included).
      return node.type === "void"
        ? code.replace(/\} \);\n$/, "}, 'void' );\n")
        : code;
    }
    emitVariables(
      node: Parameters<TSLEncoder["emitVariables"]>[0],
      root = true,
    ) {
      const next = node.next;
      node.next = null;
      (node as typeof node & { needsToVar: boolean }).needsToVar = Boolean(
        node.value,
      );
      let result = super.emitVariables(node, root);
      node.next = next;
      if (next) result += ", " + this.emitVariables(next, false);
      return result;
    }
  }
  const encoder = new PortEncoder();
  encoder.iife = true;
  const decoder = new GLSLDecoder();
  let code = new Transpiler(decoder, encoder).parse(source);
  code = code
    .replace(
      "( function ( TSL, uniforms ) {",
      `export function ${name}( bindings ) {`,
    )
    .replace(/\n\} \);\s*$/, "\n}")
    .replace(/return \{[^\n]+\};\n(?=\n\})/, "return main();\n");
  code = code.replace(/(\w+)\[\s*(\d+)\s*\]/g, "$1.element($2)");
  code = code.replace(/\b(false|true)\.toVar\(\)/g, "TSL.bool($1).toVar()");
  // out parameters must retain the caller's variable, rather than copying it.
  code = code
    .replace(/const (pos|vel) = \1_immutable.toVar\(\);/g, "")
    .replace(/\b(pos|vel)_immutable\b/g, "$1");
  code = code.replace(
    /const \{ ([^}]+) \} = TSL;/,
    (_, names) =>
      "const { " +
      names
        .split(", ")
        .filter(
          (n: string) =>
            !["uv", "modelViewMatrix", "screenCoordinate"].includes(n),
        )
        .join(", ") +
      " } = TSL;",
  );
  const preamble = Object.keys(bindings)
    .map((key) => `const ${key} = bindings.${key};`)
    .join("\n");
  const builtin = `const { cameraProjectionMatrix: projectionMatrix, modelViewMatrix, modelWorldMatrix: modelMatrix, cameraViewMatrix: viewMatrix, normalLocal: normal, positionLocal: position, screenCoordinate } = TSL;\nconst uv = TSL.uv();\n`;
  code = code.replace(
    /(export function [^{]+\{)/,
    `$1\n${preamble}\n${builtin}`,
  );
  output += "\n" + code + "\n";
  output += `export const ${name}Bindings = ${JSON.stringify(bindings)};\n`;
}
await writeFile("src/lib/vfx-lab/shaders-v2-nodes.js", output);
