// Reuse the numerically validated SPIRV-Cross kernel bodies, not the Unity wrapper.
// No external compiler is necessary to regenerate these checked-in HLSL files.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const source=path.resolve(here,'../../frontend/public/engine-export/Unity');
const shaderDir=path.join(here,'AutoV/Shaders/Private');
fs.mkdirSync(shaderDir,{recursive:true});
let cpp='// Generated by adapters/unreal/generate-shaders.mjs\n';
for(const name of ['particle','surface']) {
  const bindings=JSON.parse(fs.readFileSync(path.join(source,`${name}.bindings.json`),'utf8')).filter(b=>b.type!=='sampler2D');
  const layout=[{name:'modelMatrix',type:'mat4',size:4,slot:0},{name:'viewMatrix',type:'mat4',size:4,slot:4},{name:'projectionMatrix',type:'mat4',size:4,slot:8},{name:'modelViewMatrix',type:'mat4',size:4,slot:12},{name:'normalMatrix',type:'mat3',size:3,slot:16},{name:'cameraPosition',type:'vec3',size:0,slot:19}];
  let slot=20;
  for(const b of bindings) {layout.push({...b,slot});slot+=b.size||1;}
  if(slot>512) throw new Error('Uniform buffer overflow');
  cpp+=`static const FAutoVBinding ${name}Bindings[] = {\n`+layout.map(b=>`{TEXT("${b.name}"), ${b.slot}, ${b.size||0}, ${b.type==='int'?0:b.type==='mat4'?16:b.type==='mat3'?9:Number(b.type.slice(-1))||1}},`).join('\n')+'\n};\n';
  const unity=fs.readFileSync(path.join(source,`${name}.shader`),'utf8').replaceAll('\r\n','\n');
  let [vs,ps]=unity.split('#if defined(SHADER_STAGE_VERTEX)\n')[1].split('\n#else\n');
  ps=ps.split('\n#endif')[0];
  for(const [stage,body] of [['VS',vs],['PS',ps]]) {
    let code=body;
    let prefix='#include "/Engine/Public/Platform.ush"\nfloat4 AvfxUniforms[512];\n';
    for(const b of layout) {
      const htype=b.type==='mat4'?'float4x4':b.type==='mat3'?'float3x3':b.type.replace('vec','float');
      const regex=new RegExp(`(?:row_major\\s+)?${b.size&&b.type.startsWith('vec')||b.size&&b.type==='float'?'float4':htype}\\s+${b.name}(?:\\[${b.size}\\])?\\s*;`);
      if(!regex.test(code)) throw new Error(`Missing declaration ${name}/${stage}/${b.name}`);
      code=code.replace(regex,'');
      if(b.type.startsWith('mat')) {
        prefix+=`#define ${b.name} ${htype}(${Array.from({length:b.size},(_,i)=>`AvfxUniforms[${b.slot+i}]${b.size===3?'.xyz':''}`).join(',')})\n`;
      } else if(b.size) {
        code=code.replace(new RegExp(`\\b${b.name}\\[([^\\]]+)\\]`,'g'),`AvfxUniforms[${b.slot}+($1)]`);
      } else {
        const swizzle=b.type==='float'||b.type==='int'?'x':b.type==='vec2'?'xy':b.type==='vec3'?'xyz':'xyzw';
        prefix+=`#define ${b.name} (${b.type==='int'?'int':'float'+(swizzle.length===1?'':swizzle.length)}(AvfxUniforms[${b.slot}].${swizzle}))\n`;
      }
    }
    if(stage==='VS') {
      code=code.replace(/: POSITION\b/g,': ATTRIBUTE0').replace(/: NORMAL\b/g,': ATTRIBUTE1');
      // Only input UV semantics: output varyings retain TEXCOORDn.
      code=code.replace(/struct SPIRV_Cross_Input\s*\{([\s\S]*?)\};/,(_,b)=>'struct SPIRV_Cross_Input {'+b.replace(/TEXCOORD0/g,'ATTRIBUTE2').replace(/TEXCOORD1/g,'ATTRIBUTE3')+'};');
      code=code.replace('stage_output.gl_Position = gl_Position;', 'stage_output.gl_Position = gl_Position;\n    stage_output.gl_Position.z = (gl_Position.z + gl_Position.w) * 0.5;');
    } else {
      // Source RH/Y-up geometry is retained. D3D's viewport orientation makes
      // front-facing agree with source CCW when the rasterizer winding is set.
      code=code.replace('gl_FrontFacing = !stage_input.gl_FrontFacing;','gl_FrontFacing = stage_input.gl_FrontFacing;');
    }
    fs.writeFileSync(path.join(shaderDir,`${name}${stage}.usf`),prefix+code);
  }
}
fs.writeFileSync(path.join(here,'AutoV/Source/AutoVRuntime/Private/AutoVBindings.inl'),cpp);
console.log('Generated particle/surface HLSL and matching float4 binding layouts.');
